config/routes.rb
Rails.application.routes.draw do
  resources :businesses
  post 'upload' => 'businesses#upload'

   root 'businesses#index'

end

app/models/business.rb
class Business < ActiveRecord::Base
  validates_presence_of :name, :address, :postal_code, :country, :latitude, :longitude

  reverse_geocoded_by :latitude, :longitude
  #after_validation :reverse_geocode 

  def self.close_to_home
    Business.near(latitude: 33.1243208, longitude: -117.32582479999996)
  end

  def self.upload file
    if file.content_type == "text/tab-separated-values"
      tsv_text = File.read(file.tempfile)
      csv = CSV.parse(tsv_text, :col_sep => "\t")
      csv[1..-1].each do |v|
        name = v[0]
        #address_1 = nil
        address_1 = v[1]
        address_2 = v[2]
        postal_code = v[3]
        postal_code_suffix = v[4]
        phone_number = v[5]
        latitude = v[6]
        longitude = v[7]
        radius = v[8]
        # implement country save with lat/long and geocode
        country = 'US'
        business_params = {name: name, address: address_1, postal_code: postal_code, country: country, latitude: latitude, longitude: longitude}
        @business = Business.create!(business_params) 
      end
    else
      @business = nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/businesses_controller.rb
require 'csv'
require 'pry'
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upload
    @business = Business.upload(params[:file]) unless params[:file] == nil
    if params[:file] == nil
      flash[:danger] = 'That was an empty submit'
    end
    if @business
      respond_to do |format|
        format.html { redirect_to businesses_url, notice: 'Businesses were successfully uploaded.' }
      end
    else
      respond_to do |format|
        format.html { redirect_to new_business_url, notice: 'Something was wrong with your TSV' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :address, :postal_code, :country, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/_form_tsv.html.erb
<%= form_tag '/upload', multipart: true do %>
  <div class="field">
    <%= label_tag :Upload_Tsv %>
    <%= file_field_tag :file %>
  </div>
  <div class="actions">
    <%= submit_tag :upload %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'refills/index_hero'  %>
<%= render 'refills/tables'  %>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form_tsv' %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @business.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @business.postal_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @business.country %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @business.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @business.longitude %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChocolateMacchiato</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/refills/_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="" class="hero-logo"><img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png
" alt="Logo Image"></a>
		<div class="hero-copy">
			<h1>Short description of Product</h1>
			<p>A few reasons why this product is worth using, who it's for and why they need it.</p>	
		</div>
    <button>Learn More</button>
	</div>
</div>

app/views/refills/_index_hero.html.erb
<div class="hero">
	<div class="hero-inner">
    <a href="/" class="hero-logo"><img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_2.png" alt="Logo Image"></a>
		<div class="hero-copy">
      <h1>Close To Homebase</h1>
			<p>The closest businesses to Verve</p>	
		</div>
	</div>
</div>

app/views/refills/_tables.html.erb
<table class="tables">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Postal code</th>
      <th>Country</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.address %></td>
        <td><%= business.postal_code %></td>
        <td><%= business.country %></td>
        <td><%= business.latitude %></td>
        <td><%= business.longitude %></td>
        <td class="edit-business"><%= button_to 'Show', business_path(business), method: :get %></td>
        <td class="edit-business"><%= button_to 'Edit', edit_business_path(business), method: :get %></td>
        <td class="edit-business"><%= button_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>